insert into roles (id, username, role) values (1, 'thomas', 'admin');
insert into roles (id, username, role) values (2, 'thomas', 'manager');
insert into roles (id, username, role) values (3, 'thomas', 'Guiberest-Reader');
insert into roles (id, username, role) values (4, 'thomas', 'Guiberest-Writer');
insert into roles (id, username, role) values (5, 'roger', 'limited');
insert into users (id, password, secret) values ('thomas', 'password', '123456789');
insert into users (id, password, secret) values ('roger', 'password', '987654321');
insert into acl (id, username, role_id, access, class, pk) values (1, 'thomas', null, 'write', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.User', 'thomas');
insert into acl (id, username, role_id, access, class, pk) values (2, 'thomas', null, 'read', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.User', 'roger');
insert into acl (id, username, role_id, access, class, pk) values (3, 'thomas', null, 'read', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.Role', '1');
insert into acl (id, username, role_id, access, class, pk) values (4, null, 2, 'read', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.Role', '2');
insert into acl (id, username, role_id, access, class, pk) values (5, null, 3, 'read', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.Role', '3');
insert into acl (id, username, role_id, access, class, pk) values (6, null, 4, 'write', 'edu.swmed.qbrc.guiberest.shared.domain.guiberest.Role', '5');
